Changes to webview_cgo.go
- Previously, setting 'export JSC_SIGNAL_FOR_GC=30' prevented an error
  in which webkit complained that SIGUSR1 (10) was in use.  It is the
  signal webkit uses to trigger garbage collection.
- The way around this problem was setting the export but that stopped
  working for some reason
- In the course of trying to debug this, made some changes to
  webkit_cgo.go that **may** be more appropriate by using webkit's event
  loop thread but this new problem was unaffected and it results in this
  message if you do the export:
- Overriding existing handler for signal 30. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
 ERROR: invalid option: JSC_SIGNAL_FOR_GC=30
 - What seems to have changed is webkit now thinks signal 30 is in use
   although then generates the error above
- So current plan is to keep the changes (even though they didn't fix
  the problem) and remove the export from .bashrc
- Reminder:  You have to issue ctrl-w every time you want webkit to
  render a note